artifact_location: file:///C:/Users/HP/Desktop/DIY_TransferLearning/runs/mlflow/0
creation_time: 1729262619156
experiment_id: '0'
last_update_time: 1729262619156
lifecycle_stage: active
name: Default
